---
# vars file for add-rule
panos_ip_address: ''
panos_username: ''
panos_password: ''
panos_provider: 
  ip_address: "{{ panos_ip_address }}"
  username: "{{ panos_username }}"
  password: "{{ panos_password }}"
panos_rule_name: ""
panos_description: ""
paloalto: "true"
both: ""
panos_source_zone: []
panos_dest_zone: []
panos_source_ip: []
panos_dest_ip: []
panos_application: []
panos_service: []
jun_host: ""
jun_username: ""
jun_password: ""
jun_provider:
  host: "{{ jun_host }}"
  password: "{{ jun_password }}"
  username: "{{ jun_username }}"
jun_source_zone: ""
jun_dest_zone: ""
jun_source_address: ""
jun_dest_address: ""
jun_policy_name: ""
jun_application: ""
juniper: ""
